package adept.sbt

import sbt._
import adept.repository.models.LockFileRequirement

object AdeptKeys {
  val adeptDirectory = settingKey[File]("Adept's home directory. Defaults to: ~/.adept")
  val adeptClasspath = taskKey[Seq[Attributed[File]]]("Classpath generated by adept")
  val adeptLockFile = settingKey[File]("Adept's lock file name. Defaults to: adept.lock")
  val adeptSshPassphrase = settingKey[Option[String]]("Passphrase to .ssh credentials used by Git")
  val adeptRequirements = taskKey[Seq[LockFileRequirement]]("Adept's requirements read from lockfile")
}